### ISSUE TITLE
Override isomorphic-style-loader in the request behave different on client and backed

### ISSUE THREAD

**Issue by Everettss** [kriasoft/isomorphic-style-loader#46]
## Problem

Webpack setup from [react-starter-kit](https://github.com/kriasoft/react-starter-kit/blob/master/tools/webpack.config.js) create different output on client and backend build when use custom loaders in request #36.

## Setup
**component with styles** - I want to disable modules in css-loader since is external library

```javascript
import s from '!isomorphic-style!css-loader?modules=false!react-select/dist/react-select.css';
const Select = withStyles(s)(require('react-select'));

// ...
 <Select />
// ...
```

**loader in weback** - common setup for client and backend (from [react-starter-kit](https://github.com/kriasoft/react-starter-kit/blob/master/tools/webpack.config.js#L76-L90))

```javascript
{
  test: /\.css/,
  loaders: [
    'isomorphic-style-loader',
    `css-loader?${JSON.stringify({
      sourceMap: DEBUG,
      // CSS Modules https://github.com/css-modules/css-modules
      modules: true,
      localIdentName: DEBUG ? '[name]_[local]_[hash:base64:3]' : '[hash:base64:4]',
      // CSS Nano http://cssnano.co/options/
      minimize: !DEBUG,
    })}`,
    'postcss-loader?pack=default',
  ],
},
```

## Output 
When I use `DEBUG = false`:

**client side** is minimize
```css
.Select{position:relative}.Select,.Select div,.Select input,.Select span{box-sizing:border-box}.Select.is-disabled>.Select-control{background-color:#f9f9f9}
```

**backend side** is not minimize
```css
/**
 * React Select
 * ============
 * Created by Jed Watson and Joss Mackison for KeystoneJS, http://www.keystonejs.com/
 * https://twitter.com/jedwatson https://twitter.com/jossmackison https://twitter.com/keystonejs
 * MIT License: https://github.com/keystonejs/react-select
*/
.Select {
  position: relative;
}
.Select,
.Select div,
.Select input,
.Select span {
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
}
```
## Tips

It looks that when backend is generated it wipes out all settings from `loader` in webpack - since `minimize` is by default `false`. But why is not doing the same on the client side?
