### ISSUE TITLE
keyframes in :global don't work

### ISSUE THREAD

**Issue by PirtleShell** [kriasoft/isomorphic-style-loader#80]
I included some CSS animation keyframes under `:global` at the root of my app. The keyframe names don't render in the global scope, and they are wrapped in curly brackets. When the keyframes are used in other global classes, they do not take on the scoped name.

An example:
```css
/* Layout.css */
:global {
   .slide-enter {
      animation: slide-in 0.5s forwards;
      -webkit-animation: slide-in 0.5s forwards;
   }
   @keyframes slide-in {
      100% { transform: translateX(0%); }
   }
}
```

gets included as:
```css
{
  @keyframes Layout-slide-in-2RRX8 {
    100% { -webkit-transform: translateX(0%); transform: translateX(0%); }
  }
}
.slide-enter {
  animation: slide-in 0.5s forwards;
  -webkit-animation: slide-in 0.5s forwards;
}
```

Thoughts?

**Comment by frenzzy** [comment]
`isomorphic-style-loader` does not modify your css, so this question is mostly for [css-loader](https://github.com/webpack-contrib/css-loader) or to [css-modules](https://github.com/css-modules/css-modules) itself. But anyway you can try something like this:
```css
:global {
  .slide-enter {
    animation: slide-in 0.5s forwards;
  }
}

@keyframes :global(slide-in) {
  100% {
    transform: translateX(0);
  }
}
```
